<a href="https://colab.research.google.com/github/NoahLee99/ML-DL-studylog/blob/main/Chapter%2005-2%20-%20%EA%B5%90%EC%B0%A8%20%EA%B2%80%EC%A6%9D%EA%B3%BC%20%EA%B7%B8%EB%A6%AC%EB%93%9C%20%EC%84%9C%EC%B9%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**키워드**: [검증 세트, 교차 검증, 그리드 서치, 랜덤 서치]
  

*   검증 세트
          하이퍼파라미터 튜닝을 위해 모델을 평가할 때,
          테스트 세트를 사용하지 않기 위해 훈련 세트에서
          다시 떼어 낸 데이터 세트
*   교차 검증
          훈련 세트를 여러 폴드로 나눈 다음
          한 폴드가 검증 세트의 역할을 하고
          나머지 폴드에서는 모델을 훈련한다.
          이런 식으로 모든 폴드에 대해
          검증 점수를 얻어 평균하는 방법

*   그리드 서치
          하이퍼파라미터 탐색을 자동화해 주는 도구
          탐색할 매개변수를 나열하면 교차 검증을 수행하여
          가장 좋은 검증 점수의 매개변수 조합을 선택한다.
          마지막으로 이 매개변수 조합으로 최종 모델을 훈련한다.
*   랜덤 서치
          연속된 매개변수 값을 탐색할 때 유용하다.
          탐색할 값을 직접 나열하는 것이 아니고
          탐색 값을 샘플링할 수 있는 확률 분포 객체를 전달함.
          지정된 횟수만큼 샘플링하여 교차 검증을 수행하기 때문에
          시스템 자원이 허락하는 만큼 탐색량을 조절할 수 있다.

**핵심 패키지 및 함수**:<br>
[cross_validate(),  GridSearchCV,  RandomizedSearchCV]


*   cross_validate()
          교차 검증을 수행하는 함수이다.
          첫 번째 매개변수에 교차 검증을 수행할 모델 객체를 전달.
          두 번재와 세 번째 매개변수에 특성과 타깃 데이터를 전달.

          scoring 매개변수에 검증에 사용할 평가 지표를 지정 가능.
          기본적으로 분류 모델은 정확도를 의미하는 'accuracy',
          회귀 모델은 결정계수를 의미하는 'r2'가 된다.

          cv 매개변수에 교차 검증 폴드 수나 스플리터 객체를 지정할 수 있다. 기본값은 5이다.
          회귀할 때는 KFold 클래스를 사용하고 분류일 때는
          StratifiedKFold 클래스를 사용하여 5-폴드 교차 검증을 수행한다.

          n_jobs 매개변수는 교차 검증을 수행할 때 사용할 CPU 코어 수를 지정한다.
          기본값은 1로 하나의 코어를 사용한다.
          -1로 지정하면 시스템에 있는 모든 코어를 사용한다.

          return_train_score 매개변수를 True로 지정하면 훈련 세트의 점수도 반환한다.
          기본값은 False이다.
          
*   GridSearchCV
          교차 검증으로 랜덤한 하이퍼파라미터 탐색을 수행한다.
          최상의 모델을 찾은 후 훈련 세트 전체를 사용해 최종 모델을 훈련한다.
          첫 번째 매개변수로 그리드 서치를 수행할 모델 객체를 전달한다.
          두 번째 매개변수에는 탐색할 모델의 매개변수와 확률 분포 객체를 전달한다.

          scoring, cv, n_jobs, return_train_score 매개변수는
          cross_validat() 함수와 동일하다.







In [ ]:
'''
이번 장에서는 테스트 세트로 평가를 하면 할수록 테스트 세트에 과적합되는 문제를 해결하기 위한 방법을 배울 예정이다.
지금가지 우리는 훈련 세트에서 모델을 훈련하고 테스트 세트에서 모델을 평가했다.
테스트 세트에서 얻은 점수를 보고, 새로운 데이터로 성능을 평가했을 때의 성능 정도를 예측했다.
이를 "일반화 성능"이라 하며, 모델이 학습 데이터뿐만 아니라 이전에 보지 못한 새로운 데이터에도 잘 작동하는 능력을 의미한다.
테스트 세트로 일반화 성능을 올바르게 예측하려면 가능한 한 테스트 세트를 사용하지 말아야 한다.
모델을 만들고 나서 마지막에 딱 한 번만 사용하는 것이 좋다.

그렇다면 max_depth 매개변수를 사용한 "하이퍼파라미터 튜닝"을 어떻게 할 수 있을까?
(하이퍼파라미터 튜닝은 머신러닝 모델의 성능을 최적화하는데 필수적인 과정이다.)
테스트 세트를 사용하지 않으면 모델이 과대적합인지 과소적합인지 판단하기 어렵다
테스트 세트의 사용 없이 이를 측정하는 간단한 방법은 무엇일가?
바로 훈련 세트를 또 나누는 것이다!
이를 "검증 세트(validation set)"라고 부른다.
이는 실제로 많이 사용하는 방법이며, 80%로 만든 훈련 세트를 또 다시 20%를 떼어 내어 검증 세트로 만든다.
(훈련: 60%, 검증: 20%, 테스트: 20%)
보통 20~30%를 테스트 세트와 검증 세트로 떼어 놓지만 문제에 따라 다르다.
훈련 데이터가 아주 많다면 단 몇 %만 떼어 놓아도 전체 데이터를 대표하는 데 문제가 없다.

훈련 세트에서 모델을 훈련하고 검증 세트로 모델을 평가한다.
이런 식으로 테스트하고 싶은 매개변수를 바꿔가며 가장 좋은 모델을 고른다.
그 다음 최적의 매개변수를 사용해 훈련 세트와 검증 세트를 합쳐 전체 훈련 데이터에서 모델을 다시 훈련한다.
그리고 마지막에 테스트 세트에서 최종 점수를 평가한다.
실전에 투입했을 때 테스트 세트의 점수와 비슷한 성능을 기대할 수 있을 것이다.
'''

'\n이번 장에서는 테스트 세트로 평가를 하면 할수록 테스트 세트에 과적합되는 문제를 해결하기 위한 방법을 배울 예정이다.\n지금가지 우리는 훈련 세트에서 모델을 훈련하고 테스트 세트에서 모델을 평가했다.\n테스트 세트에서 얻은 점수를 보고, 새로운 데이터로 성능을 평가했을 때의 성능 정도를 예측했다.\n이를 "일반화 성능"이라 하며, 모델이 학습 데이터뿐만 아니라 이전에 보지 못한 새로운 데이터에도 잘 작동하는 능력을 의미한다.\n테스트 세트로 일반화 성능을 올바르게 예측하려면 가능한 한 테스트 세트를 사용하지 말아야 한다.\n모델을 만들고 나서 마지막에 딱 한 번만 사용하는 것이 좋다.\n\n그렇다면 max_depth 매개변수를 사용한 "하이퍼파라미터 튜닝"을 어떻게 할 수 있을까?\n(하이퍼파라미터 튜닝은 머신러닝 모델의 성능을 최적화하는데 필수적인 과정이다.)\n테스트 세트를 사용하지 않으면 모델이 과대적합인지 과소적합인지 판단하기 어렵다\n테스트 세트의 사용 없이 이를 측정하는 간단한 방법은 무엇일가?\n바로 훈련 세트를 또 나누는 것이다!\n이를 "검증 세트(validation set)"라고 부른다.\n이는 실제로 많이 사용하는 방법이며, 80%로 만든 훈련 세트를 또 다시 20%를 떼어 내어 검증 세트로 만든다.\n(훈련: 60%, 검증: 20%, 테스트: 20%)\n보통 20~30%를 테스트 세트와 검증 세트로 떼어 놓지만 문제에 따라 다르다.\n훈련 데이터가 아주 많다면 단 몇 %만 떼어 놓아도 전체 데이터를 대표하는 데 문제가 없다.\n\n훈련 세트에서 모델을 훈련하고 검증 세트로 모델을 평가한다.\n이런 식으로 테스트하고 싶은 매개변수를 바꿔가며 가장 좋은 모델을 고른다.\n그 다음 최적의 매개변수를 사용해 훈련 세트와 검증 세트를 합쳐 전체 훈련 데이터에서 모델을 다시 훈련한다.\n그리고 마지막에 테스트 세트에서 최종 점수를 평가한다.\n실전에 투입했을 때 테스트 세트의 점수와 비슷한 성능을 기대할 수 있을 것이다.\n'

In [ ]:
# 이전 장에서 사용한 데이터 리로드 후 검증 세트 생성
import pandas as pd

wine = pd.read_csv('https://bit.ly/wine_csv_data')

In [ ]:
# class 열을 타깃으로 사용하고 나머지 열은 특성 배열에 저장
data = wine[['alcohol', 'sugar', 'pH']].to_numpy()

target = wine['class'].to_numpy()

In [ ]:
# 훈련 세트와 테스트 세트 나누기
from sklearn.model_selection import train_test_split
train_input, test_input, train_target, test_target = train_test_split(
    data, target, test_size=0.2, random_state=42)

In [ ]:
# 훈련 세트와 검증 세트 생성
sub_input, val_input, sub_target, val_target = train_test_split(
    train_input, train_target, test_size=0.2, random_state=42)

# sub_input, sub_target의 생성은 train_test_split() 함수를 사용하여 훈련 세트를 다시 검증 세트로 나누기 위함임

In [ ]:
# 훈련 세트와 검증 세트의 크기를 확인
print(sub_input.shape, val_input.shape)

(4157, 3) (1040, 3)


In [ ]:
# 훈련 세트와 검증 세트를 사용해 모델 생성 후 평가
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(random_state=42)
dt.fit(sub_input, sub_target)

print(dt.score(sub_input, sub_target))
print(dt.score(val_input, val_target))

# 훈련 세트에 과대적합된 것을 확인할 수 있음 --> 매개변수를 바꿔 더 좋은 모델을 찾아야 함

0.9971133028626413
0.864423076923077


In [ ]:
'''
현재 검증 세트를 만드느라 훈련 세트가 줄었다.
보통 많은 데이터를 훈련에 사용할수록 좋은 모델이 만들어진다.
그렇다고 검증 세트를 너무 조금 떼어 놓으면 검증 점수가 들쭉날쭉하고 불안정할 것이다.
이럴 때 "교차 검증(cross validation)"을 이용하면 안정적인 검증 점수를 얻고 훈련에 더 많은 데이터를 사용 가능하다.

교차 검증은 검증 세트를 떼어 내어 평가하는 과정을 여러 번 반복한다.
그다음 이 점수를 평균하여 최종 검증 점수를 얻는다.
즉 데이터를 여러 개의 fold로 나누어 각 fold를 검증 세트로 사용하여 모델을 반복적으로 학습하고 평가하는 방법이다.

EX)
[훈련 세트 / 훈련 세트 / 검증 세트]: 1,2 폴드 사용
[훈련 세트 / 검증 세트 / 훈련 세트]: 1,3 폴드 사용
[검증 세트 / 훈련 세트 / 훈련 세트]: 2,3 폴드 사용

"3-폴드 교차 검증"이란 훈련 세트를 세 부분으로 나눠서 교차 검증을 수행하는 것을 말한다.
통칭 "K-폴드 교차 검증(K-fold cross validation)이라고 하며, 훈련 세트를 몇 부분으로 나누냐에 따라 다르게 부른다.
K-겹 교차 검증이라고도 부른다.
보토 5-폴드 교차 검증이나 10-폴드 교차 검증을 많이 사용한다.
이렇게 하면 데이터의 80~90%까지 훈련에 사용할 수 있다.
검증 세트가 줄어들지만 각 폴드에서 계산한 검증 점수를 평균하기 때문에 안정된 점수로 생각할 수 있다.
'''

'\n현재 검증 세트를 만드느라 훈련 세트가 줄었다.\n보통 많은 데이터를 훈련에 사용할수록 좋은 모델이 만들어진다.\n그렇다고 검증 세트를 너무 조금 떼어 놓으면 검증 점수가 들쭉날쭉하고 불안정할 것이다.\n이럴 때 "교차 검증(cross validation)"을 이용하면 안정적인 검증 점수를 얻고 훈련에 더 많은 데이터를 사용 가능하다.\n\n교차 검증은 검증 세트를 떼어 내어 평가하는 과정을 여러 번 반복한다.\n그다음 이 점수를 평균하여 최종 검증 점수를 얻는다.\n즉 데이터를 여러 개의 fold로 나누어 각 fold를 검증 세트로 사용하여 모델을 반복적으로 학습하고 평가하는 방법이다.\n\nEX) \n[훈련 세트 / 훈련 세트 / 검증 세트]: 1,2 폴드 사용\n[훈련 세트 / 검증 세트 / 훈련 세트]: 1,3 폴드 사용\n[검증 세트 / 훈련 세트 / 훈련 세트]: 2,3 폴드 사용\n\n"3-폴드 교차 검증"이란 훈련 세트를 세 부분으로 나눠서 교차 검증을 수행하는 것을 말한다.\n통칭 "K-폴드 교차 검증(K-fold cross validation)이라고 하며, 훈련 세트를 몇 부분으로 나누냐에 따라 다르게 부른다.\nK-겹 교차 검증이라고도 부른다.\n보토 5-폴드 교차 검증이나 10-폴드 교차 검증을 많이 사용한다.\n이렇게 하면 데이터의 80~90%까지 훈련에 사용할 수 있다.\n검증 세트가 줄어들지만 각 폴드에서 계산한 검증 점수를 평균하기 때문에 안정된 점수로 생각할 수 있다.\n'

In [ ]:
# 사이킷런의 교차 검증 함수를 사용
# 1. 평가할 모델 객체를 함수의 첫 번째 매개변수로 전달
# 2. 직접 검증 세트를 떼어 내지 않고, 훈련 세트 전체를 함수에 전달
from sklearn.model_selection import cross_validate

scores = cross_validate(dt, train_input, train_target)

print(scores)

# 사이킷런에는 cross_validate() 함수의 전신인 cross_val_score() 함수도 있음
# 이 함수는 cross_validate() 함수의 결과 중 test_score 값만 반환함

{'fit_time': array([0.01085281, 0.00937128, 0.00931787, 0.01145935, 0.00889039]), 'score_time': array([0.00175667, 0.00173783, 0.00211358, 0.00193787, 0.00159431]), 'test_score': array([0.86923077, 0.84615385, 0.87680462, 0.84889317, 0.83541867])}


In [ ]:
'''
cross_validate() 함수는 fit_time, score_time, test_score 키를 가진 딕셔너리를 반환한다.
처음 2개의 키는 각각 모델을 훈련하는 시간과 검증하는 시간을 의미한다.
각 키마다 5개의 숫자가 담겨 있다.
cross_validate() 함수는 기본적으로 5-폴드 교차 검증을 수행한다.
cv 매개변수에서 폴드 수를 바꿀 수도 있다.

교차 검증의 최종 점수는 test_score 키에 담긴 5개의 점수를 평균하여 얻을 수 있다.
이름은 test_score지만 검증 폴드의 점수이니 혼동하지 말 것.
'''

'\ncross_validate() 함수는 fit_time, score_time, test_score 키를 가진 딕셔너리를 반환한다.\n처음 2개의 키는 각각 모델을 훈련하는 시간과 검증하는 시간을 의미한다.\n각 키마다 5개의 숫자가 담겨 있다.\ncross_validate() 함수는 기본적으로 5-폴드 교차 검증을 수행한다.\ncv 매개변수에서 폴드 수를 바꿀 수도 있다.\n\n교차 검증의 최종 점수는 test_score 키에 담긴 5개의 점수를 평균하여 얻을 수 있다.\n이름은 test_score지만 검증 폴드의 점수이니 혼동하지 말 것.\n'

In [ ]:
import numpy as np

print(np.mean(scores['test_score']))

0.855300214703487


In [ ]:
'''
이렇게 교차 검증을 수행하면 입력한 모델에서 얻을 수 있는 최상의 검증 점수를 가늠해 볼 수 있다.
한 가지 주의할 점은 cross_validate()는 훈련 세트를 섞어 폴드를 나누지 않는다.
앞서 나는 train_test_split() 함수로 전체 데이터를 섞은 후 훈련 세트를 준비했기 때문에 따로 섞을 필요가 없다.

만약 교차 검증을 할 때 훈련 세트를 섞으려면 분할기(splitter)를 지정해야 한다.
사이킷런의 분할기는 교차 검증에서 폴드를 어떻게 나눌지 결정해 준다.
cross_validate() 함수는 기본적으로 회귀 모델일 경우 KFold 분할기를 사용하고,
분류 모델일 경우 타깃 클래스를 골고루 나누기 위해 StratifiedKFold를 사용한다.

앞서 수행한 교차 검증은 다음 코드와 동일하다.
'''

'\n이렇게 교차 검증을 수행하면 입력한 모델에서 얻을 수 있는 최상의 검증 점수를 가늠해 볼 수 있다.\n한 가지 주의할 점은 cross_validate()는 훈련 세트를 섞어 폴드를 나누지 않는다.\n앞서 나는 train_test_split() 함수로 전체 데이터를 섞은 후 훈련 세트를 준비했기 때문에 따로 섞을 필요가 없다.\n\n만약 교차 검증을 할 때 훈련 세트를 섞으려면 분할기(splitter)를 지정해야 한다.\n사이킷런의 분할기는 교차 검증에서 폴드를 어떻게 나눌지 결정해 준다.\ncross_validate() 함수는 기본적으로 회귀 모델일 경우 KFold 분할기를 하용하고, \n분류 모델일 경우 타깃 클래스를 골고루 나누기 위해 StratifiedKFold를 사용한다.\n\n앞서 수행한 교차 검증은 다음 코드와 동일하다.\n'

In [ ]:
from sklearn.model_selection import StratifiedKFold

scores = cross_validate(dt, train_input, train_target, cv=StratifiedKFold())

print(np.mean(scores['test_score']))

0.855300214703487


In [ ]:
# 만약 훈련 세트를 섞은 후 10-폴드 교차 검증을 수행시
splitter = StratifiedKFold(n_splits=10, shuffle=True, random_state=42) # n_splits 매개변수는 몇(k) 폴드 교차 검증 할지 정해줌

scores = cross_validate(dt, train_input, train_target, cv=splitter)

print(np.mean(scores['test_score']))

0.8574181117533719


In [ ]:
'''
이제 교차 검증에 대한 이해를 바탕으로 이어서
결정 트리의 매개변수 값을 바꿔가며 가장 좋은 성능이 나오는 모델을 찾아 볼 것이다.
이때 테스트 세트를 사용하지 않고 교차 검증을 통해서 좋은 모델을 고르면 된다.

이러한 하이퍼파라미터 튜닝 작업은 어떻게 진행할까?
먼저 라이브러리가 제공하는 기본값을 그대로 사용해 모델을 훈련한다.
그다음 검증 세트의 점수나 교차 검증을 통해서 매개변수를 조금씩 바꿔 본다.
모델마다 적게는 1~2개에서, 많게는 5~6개의 매개변수를 제공한다.
이 매개변수를 바꿔가면서 모델을 훈련하고 교차 검증을 수행해야 한다.

사람의 개입 없이 하이퍼파라미터 튜닝을 자동으로 수행하는 기술을 'AutoML'이라고 부른다.

여기 아주 중요한 점이 있다.
가령 결정 트리 모델에서 최적의 max_depth 값을 찾았다고 가정해 보자.
그다음 max_depth를 최적의 값으로 고정하고 min_samples_split을 바꿔가며 최적의 값을 찾는다.
이렇게 한 매개변수의 최적값을 찾고 다른 매개변수의 최적값을 찾아도 될까?
아니다! max_depth의 최적값은 min_samples_split 매개변수의 값이 바뀌면 함께 달라진다.
즉 이 매개변수들을 동시에 바꿔가며 최적의 값을 찾아야 하는 것이다.

파이썬의 for문(반복)으로 이런 과정을 직접 구현할 수도 있지만, 사이킷런에서 "그리드 서치"를 제공한다.
사이킷런의 GridSearchCV 클래스는 친절하게도 하이퍼파라미터 탐색과 교차 검증을 한 번에 수행한다.
별도로 cross_validate() 함수를 호출할 필요가 없다.

어떻게 사용하지 간단한 예시를 만들어 보자.
기본 매개변수를 사용한 결정 트리 모델에서 min_impurity_decrease 매개변수의 최적값을 찾아보겠다.
먼저 그리드 서치 클래스를 임포트하고 탐색할 값의 리스트를 딕셔너리로 만든다.
'''

'\n이제 교차 검증에 대한 이해를 바탕으로 이어서\n결정 트리의 매개변수 값을 바꿔가며 가장 좋은 성능이 나오는 모델을 찾아 볼 것이다.\n이때 테스트 세트를 사용하지 않고 교차 검증을 통해서 좋은 모델을 고르면 된다.\n\n이러한 하이퍼파라미터 튜닝 작업은 어떻게 진행할까?\n먼저 라이브러리가 제공하는 기본값을 그대로 사용해 모델을 훈련한다.\n그다음 검증 세트의 점수나 교차 검증을 통해서 매개변수를 조금씩 바꿔 본다.\n모델마다 적게는 1~2개에서, 많게는 5~6개의 매개변수를 제공한다.\n이 매개변수를 바꿔가면서 모델을 훈련하고 교차 검증을 수행해야 한다.\n\n사람의 개입 없이 하이퍼파라미터 튜닝을 자동으로 수행하는 기술을 \'AutoML\'이라고 부른다.\n\n여기 아주 중요한 점이 있다.\n가령 결정 트리 모델에서 최적의 max_depth 값을 찾았다고 가정해 보자.\n그다음 max_depth를 최적의 값으로 고정하고 min_samples_split을 바꿔가며 최적의 값을 찾는다.\n이렇게 한 매개변수의 최적값을 찾고 다른 매개변수의 최적값을 찾아도 될까?\n아니다! max_depth의 최적값은 min_samples_split 매개변수의 값이 바뀌면 함께 달라진다.\n즉 이 매개변수들을 동시에 바꿔가며 최적의 값을 찾아야 하는 것이다.\n\n파이썬의 for문(반복)으로 이런 과정을 직접 구현할 수도 있지만, 사이킷런에서 "그리드 서치"를 제공한다.\n사이킷런의 GridSearchCV 클래스는 친절하게도 하이퍼파라미터 탐색과 교차 검증을 한 번에 수행한다.\n별도로 cross_validate() 함수를 호출할 필요가 없다.\n\n어떻게 사용하지 간단한 예시를 만들어 보자.\n기본 매개변수를 사용한 결정 트리 모델에서 min_impurity_decrease 매개변수의 최적값을 찾아보겠다.\n먼저 그리드 서치 클래스를 임포트하고 탐색할 값의 리스트를 딕셔너리로 만든다.\n'

In [ ]:
from sklearn.model_selection import GridSearchCV

params = {'min_impurity_decrease': [0.0001, 0.0002, 0.0003, 0.0004, 0.0005]}

# min_impurity_decrease는 탐색할 매개변수, 0.001~0.005는 탐색할 값

In [ ]:
# 그리드 서치 객체 생성
gs = GridSearchCV(DecisionTreeClassifier(random_state=42), params, n_jobs=-1)

In [ ]:
'''
결정 트리 클래스의 객체를 생성하자마자 바로 전달했다.
그다음 일반 모델을 훈련하는 것처럼 gs 객체에 fit() 메서드를 호출한다.
이 메서드를 호출하면 그리드 서치 객체는 결정 트리 모델 min_impurity_decrease 값을 바꿔가며 총 5번 실행한다.

GridSearchCV의 cv 매개변수 기본값은 5이다.
따라서 min_impurity_decrease 값마다 5-폴드 교차 검증을 수행한다.
결국 5 * 5 = 25개의 모델을 훈련한다.
많은 모델을 훈련하기 때문에 GridSearchCV 클래스의 n_jobs 매개변수에서 병령 실행에 사용할 CPU 코어 수를 지정하는 것이 좋다.
이 매개변수의 기본값은 1이다.
-1로 지정하면 시스템에 있는 모든 코어를 사용한다.
'''

'\n결정 트리 클래스의 객체를 생성하자마자 바로 전달했다.\n그다음 일반 모델을 훈련하는 것처럼 gs 객체에 fit() 메서드를 호출한다.\n이 메서드를 호출하면 그리드 서치 객체는 결정 트리 모델 min_impurity_decrease 값을 바꿔가며 총 5번 실행한다.\n\nGridSearchCV의 cv 매개변수 기본값은 5이다.\n따라서 min_impurity_decrease 값마다 5-폴드 교차 검증을 수행한다.\n결국 5 * 5 = 25개의 모델을 훈련한다.\n많은 모델을 훈련하기 때문에 GridSearchCV 클래스의 n_jobs 매개변수에서 병령 실행에 사용할 CPU 코어 수를 지정하는 것이 좋다.\n이 매개변수의 기본값은 1이다.\n-1로 지정하면 시스템에 있는 모든 코어를 사용한다.\n'

In [ ]:
# 그리드 서치 수행
gs.fit(train_input, train_target)

GridSearchCV(estimator=DecisionTreeClassifier(random_state=42), n_jobs=-1,
             param_grid={'min_impurity_decrease': [0.0001, 0.0002, 0.0003,
                                                   0.0004, 0.0005]})

In [ ]:
'''
교차 검증에서 최적의 하이퍼파라미터를 찾으면 전체 훈련 세트로 모델을 다시 만들어야 한다고 했지만,
아주 편리하게도 사이킷런의 그리드 서치는 훈련이 끝나면 25개의 모델 중에서
검증 점수가 가장 높은 모델의 매개변수 조합으로 전체 훈련 세트에서 자동으로 다시 모델을 훈련한다.
이 모델은 gs 객채의 best_estimator_ 속성에 저장되어 있으며, 이 모델을 일반 결정 트리처럼 똑같이 사용 가능하다.
'''

'\n교차 검증에서 최적의 하이퍼파라미터를 찾으면 전체 훈련 세트로 모델을 다시 만들어야 한다고 했지만,\n아주 편리하게도 사이킷런의 그리드 서치는 훈련이 끝나면 25개의 모델 중에서 \n검증 점수가 가장 높은 모델의 매개변수 조합으로 전체 훈련 세트에서 자동으로 다시 모델을 훈련한다.\n이 모델은 gs 객채의 best_estimator_ 속성에 저장되어 있으며, 이 모델을 일반 결정 트리처럼 똑같이 사용 가능하다.\n'

In [ ]:
# 그리드 서치로 훈련된 모델 점수 출력
dt = gs.best_estimator_

print(dt.score(train_input, train_target))

0.9615162593804117


In [ ]:
# 그리드 서치로 찾은 최적 매개변수 값 출력
print(gs.best_params_)

# 최적의 매개변수 값은 best_params_ 속성에 저장됨

{'min_impurity_decrease': 0.0001}


In [ ]:
# 5번의 교차 검증으로 얻은 점수 출력
print(gs.cv_results_['mean_test_score'])

# 각 매개변수에서 수행한 교차 검증의 평균 점수는 cv_results_ 속성의 'mean_test_score' 키에 저장되어 있음

[0.86819297 0.86453617 0.86492226 0.86780891 0.86761605]


In [ ]:
# 넘파이 argmax() 함수를 사용하면 가장 큰 값의 인덱스를 추출 가능하다.
# 그다음 이 인덱스를 사용해 params 키에 저장된 매개변수를 출력할 수 있다.
# 이 값이 최상의 검증 점수를 만든 매개변수 조합이다.

# 앞서 출력한 gs.best_params_와 동일한지 확인
best_index = np.argmax(gs.cv_results_['mean_test_score'])

print(gs.cv_results_['params'][best_index])

{'min_impurity_decrease': 0.0001}


In [ ]:
'''
지금까지의 과정을 정리해 보자.

1. 먼저 탐색할 매개변수를 지정한다.
2. 그다음 훈련 세트에서 그리드 서치를 수행하여 최상의 평균 검증 점수가 나오는 매개변수 조합을 찾는다.
3. 그리드 서치는 최상의 매개변수에서 (교차 검증에 사용한 훈련 세트가 아니라) 전체 훈련 세트를 사용해 최종 모델을 훈련한다.

그렇다면 조금 더 복잡한 매개변수 조합을 탐색해 보자.
결정 트리에서 min_impurity_decrease는 노드를 분할하기 위한 불순도 감소 최소량을 지정한다.
여기다가 max_depth로 트리의 깊이를 제안하고 min_samples_split으로 노드를 나누기 위한 최소 샘플 수도 골라 보겠다.
'''

'\n지금까지의 과정을 정리해 보자.\n\n1. 먼저 탐색할 매개변수를 지정한다.\n2. 그다음 훈련 세트에서 그리드 서치를 수행하여 최상의 평균 검증 점수가 나오는 매개변수 조합을 찾는다.\n3. 그리드 서치는 최상의 매개변수에서 (교차 검증에 사용한 훈련 세트가 아니라) 전체 훈련 세트를 사용해 최종 모델을 훈련한다.\n\n그렇다면 조금 더 복잡한 매개변수 조합을 탐색해 보자.\n결정 트리에서 min_impurity_decrease는 노드를 분할하기 위한 불순도 감소 최소량을 지정한다.\n여기다가 max_depth로 트리의 깊이를 제안하고 min_samples_split으로 노드를 나누기 위한 최소 샘플 수도 골라 보겠다.\n'

In [ ]:
params = {'min_impurity_decrease': np.arange(0.0001, 0.001, 0.0001),
          'max_depth': range(5, 20, 1),
          'min_samples_split': range(2, 100, 10)
          }

In [ ]:
'''
넘파이 arange() 함수는 첫 번째 매개변수 값에서 시작하여
두 번째 매개변수에 도달할 때까지 세 번째 매개변수를 계속 더한 배열을 만든다.

파이썬 range() 함수도 비슷하다.
하지만 이 함수는 정수만 사용 가능하다.
이 경우 max_depth를 5에서 20까지 1씩 증가하면서 15개의 값을 만든다.
min_samples_split은 2에서 100까지 10씩 증가하면서 10개의 값을 만든다.

따라서 이 매배견수로 수행할 교차 검증 횟수는 9 * 15 * 10 = 1,350개이다.
기본 5-폴드 교차 검증을 수행하므로 만들어지는 모델의 수는 6,750개나 된다.
'''

'\n넘파이 arange() 함수는 첫 번째 매개변수 값에서 시작하여 \n두 번째 매개변수에 도달할 때까지 세 번째 매개변수를 계속 더한 배열을 만든다.\n\n파이썬 range() 함수도 비슷하다.\n하지만 이 함수는 정수만 사용 가능하다.\n이 경우 max_depth를 5에서 20까지 1씩 증가하면서 15개의 값을 만든다.\nmin_samples_split은 2에서 100까지 10씩 증가하면서 10개의 값을 만든다.\n\n따라서 이 매배견수로 수행할 교차 검증 횟수는 9 * 15 * 10 = 1,350개이다.\n기본 5-폴드 교차 검증을 수행하므로 만들어지는 모델의 수는 6,750개나 된다.\n'

In [ ]:
# 그리드 서치 실행
gs = GridSearchCV(DecisionTreeClassifier(random_state=42), params, n_jobs=-1)
gs.fit(train_input, train_target)

GridSearchCV(estimator=DecisionTreeClassifier(random_state=42), n_jobs=-1,
             param_grid={'max_depth': range(5, 20),
                         'min_impurity_decrease': array([0.0001, 0.0002, 0.0003, 0.0004, 0.0005, 0.0006, 0.0007, 0.0008,
       0.0009]),
                         'min_samples_split': range(2, 100, 10)})

In [ ]:
# 최상의 매개변수 조합 확인
print(gs.best_params_)

{'max_depth': 14, 'min_impurity_decrease': 0.0004, 'min_samples_split': 12}


In [ ]:
# 최상의 교차 검증 점수 확인
print(np.max(gs.cv_results_['mean_test_score']))

0.8683865773302731


In [ ]:
'''
GridSearchCV 클래스를 사용하니 매개변수를 일일이 바꿔가며 교차 검증을 수행하지 않고
원하는 매개변수 값을 나열하면 자동으로 교차 검증을 수행해서 최상의 매개변수를 찾을 수 있다.

그런데 아쉬운 점이 남아있다.
앞에서 탐색할 매개변수의 간격을 0.0001 혹은 1로 설정했는데,
이렇게 간격을 둔 것에 특별한 근거가 없다.
이보다 더 좁거나 넓은 간격으로 시도해볼 수 있지 않을까?

매개변수의 값이 수치일 때 값의 범위나 간격을 미리 정하기 어려울 수 있다.
또 너무 많은 매개변수 조건이 있어 그리드 서치 수행 시간이 오래 걸릴 수 있는데,
이럴 때 "랜덤 서치(Random Search)"를 사용하면 좋다.

랜덤 서치에는 매개변수 값의 목록을 전달하는 것이 아니라,
매개변수를 샘플링할 수 있는 확률 분포 객체를 전달한다.
먼저 싸이파이에서 2개의 확률 분포 클래스를 임포트 해보자.

"싸이파이(scipy)"라는 파이썬의 핵심 과학 라이브러리 중 하나이다.
적분, 보간, 선형 대수, 확률 등을 포함한 수치 계산 전용 라이브러리이다.
사이킷런은 넘파이와 싸이파이 기능을 많이 사용한다.
'''

'\nGridSearchCV 클래스를 사용하니 매개변수를 일일이 바꿔가며 교차 검증을 수행하지 않고\n원하는 매개변수 값을 나열하면 자동으로 교차 검증을 수행해서 최상의 매개변수를 찾을 수 있다.\n\n그런데 아쉬운 점이 남아있다.\n앞에서 탐색할 매개변수의 간격을 0.0001 혹은 1로 설정했는데,\n이렇게 간격을 둔 것에 특별한 근거가 없다.\n이보다 더 좁거나 넓은 간격으로 시도해볼 수 있지 않을까?\n\n매개변수의 값이 수치일 때 값의 범위나 간격을 미리 정하기 어려울 수 있다.\n또 너무 많은 매개변수 조건이 있어 그리드 서치 수행 시간이 오래 걸릴 수 있는데,\n이럴 때 "랜덤 서치(Random Search)"를 사용하면 좋다.\n\n랜덤 서치에는 매개변수 값의 목록을 전달하는 것이 아니라,\n매개변수를 샘플링할 수 있는 확률 분포 객체를 전달한다.\n먼저 싸이파이에서 2개의 확률 분포 클래스를 임포트 해보자.\n\n"싸이파이(scipy)"라는 파이썬의 핵심 과학 라이브러리 중 하나이다.\n적분, 보간, 선형 대수, 확률 등을 포함한 수치 계산 전용 라이브러리이다.\n사이킷런은 넘파이와 싸이파이 기능을 많이 사용한다.\n'

In [ ]:
from scipy.stats import uniform, randint

In [ ]:
'''
싸이파이의 stats 서브 패키지에 있는 uniform과 randint 클래스는 모두 주어진 범위에서 고르게 값을 뽑는다.
이를 "균등 분포에서 샘플링한다"라고 말한다.
randint는 정수값을 뽑고, uniform은 실수값을 뽑는다.
사용하는 방법은 같다.
0에서 10 사이의 범위를 갖는 randint 객체를 만들고 10개의 숫자를 샘플링해 보자.
'''

'\n싸이파이의 stats 서브 패키지에 있는 uniform과 randint 클래스는 모두 주어진 범위에서 고르게 값을 뽑는다.\n이를 "균등 분포에서 샘플링한다"라고 말한다.\nrandint는 정수값을 뽑고, uniform은 실수값을 뽑는다.\n사용하는 방법은 같다.\n0에서 10 사이의 범위를 갖는 randint 객체를 만들고 10개의 숫자를 샘플링해 보자.\n'

In [ ]:
rgen = randint(0, 10)
rgen.rvs(10)

array([3, 6, 0, 1, 6, 3, 3, 6, 5, 3])

In [ ]:
# 1,000를 샘플링 후 각 숫자의 개수를 세기
np.unique(rgen.rvs(1000), return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 84,  98,  82,  98, 105, 102,  89, 108, 130, 104]))

In [ ]:
# uniform 클래스 사용(동일)
ugen = uniform(0, 1)
ugen.rvs(10)

array([0.62781846, 0.38374722, 0.54002629, 0.028483  , 0.05282556,
       0.04837829, 0.17634906, 0.15092272, 0.76276383, 0.20589904])

In [ ]:
'''
난수 발생기랑 유사하게 생각하면 된다.
랜덤 서치에 randint와 uniform 클래스 객체를 넘겨주고 총 몇 번을 샘플링해서 최적의 매개변수를 찾으라고 명령할 수 있다.
샘플링 횟수는 시스템 자원이 허락하는 범위 내에서 최대한 크게 하는 것이 좋다.

그럼 이제 탐색할 매개변수의 딕션리를 만들어 볼 것이다.
여기에서는 min_samples_leaf 매개변수를 탐색 대상에 추가하겠다.
이 매개변수는 리프 노드가 되기 위한 최소 샘플링 개수이다.
어떤 노드가 분할하여 만들어질 자식 노드의 샘플 수가 이 값보다 작을 경우 분할하지 않는다.
'''

'\n난수 발생기랑 유사하게 생각하면 된다.\n랜덤 서치에 randint와 uniform 클래스 객체를 넘겨주고 총 몇 번을 샘플링해서 최적의 매개변수를 찾으라고 명령할 수 있다.\n샘플링 횟수는 시스템 자원이 허락하는 범위 내에서 최대한 크게 하는 것이 좋다.\n\n그럼 이제 탐색할 매개변수의 딕션리를 만들어 볼 것이다.\n여기에서는 min_samples_leaf 매개변수를 탐색 대상에 추가하겠다.\n이 매개변수는 리프 노드가 되기 위한 최소 샘플링 개수이다.\n어떤 노드가 분할하여 만들어질 자식 노드의 샘플 수가 이 값보다 작을 경우 분할하지 않는다.\n'

In [ ]:
# 탐색할 매개변수 범위
params = {'min_impurity_decrease': uniform(0.0001, 0.001),
          'max_depth': randint(20, 50),
          'min_samples_split': randint(2, 25),
          'min_samples_leaf': randint(1, 25),
          }

In [ ]:
# 샘플링 횟수는 사이킷런의 랜덤 서치 클래스인 RandomizedSearchCV의 n_iter 매개변수에 지정
from sklearn.model_selection import RandomizedSearchCV

gs = RandomizedSearchCV(DecisionTreeClassifier(random_state=42), params,
                       n_iter=100, n_jobs=1, random_state=42)
gs.fit(train_input, train_target)

# params에 정의된 매개변수 범위에서 총 100번(n_iter)을 샘플링하여 교차 검증을 수행하고 최적의 매개변수 조합을 찾음

RandomizedSearchCV(estimator=DecisionTreeClassifier(random_state=42),
                   n_iter=100, n_jobs=1,
                   param_distributions={'max_depth': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x7c52ceb4fd00>,
                                        'min_impurity_decrease': <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x7c52cb4a8af0>,
                                        'min_samples_leaf': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x7c52ceb4f8e0>,
                                        'min_samples_split': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x7c52cb4a9420>},
                   random_state=42)

In [ ]:
# 최적의 매개변수 조합을 출력
print(gs.best_params_)

{'max_depth': 39, 'min_impurity_decrease': 0.00034102546602601173, 'min_samples_leaf': 7, 'min_samples_split': 13}


In [ ]:
# 최고의 교차 검증 점수 확인
print(np.max(gs.cv_results_['mean_test_score']))

# 최적의 모델은 이미 전체 훈련 세트(train_input, train_target)로 훈련되어 best_estimator_ 속성에 저장되어 있음

0.8695428296438884


In [ ]:
# 최종 모델로 결정 후 테스트 세트의 성능 확인
dt = gs.best_estimator_

print(dt.score(test_input, test_target))

0.86


In [ ]:
'''
테스트 세트 점수는 검증 세트에 대한 점수보다 조금 작은 것이 일반적이다.
최종 테스트 점수가 아주 만족스럽지는 않지만, 다양한 매개변수를 테스트 해서 얻은 결과임은 확실하다.

앞으로 수동으로 매개변수를 바꾸는 대신에, 그리드 서치나 랜덤 서치를 사용해야겠다!
'''

'\n테스트 세트 점수는 검증 세트에 대한 점수보다 조금 작은 것이 일반적이다.\n최종 테스트 점수가 아주 만족스럽지는 않지만, 다양한 매개변수를 테스트 해서 얻은 결과임은 확실하다.\n\n앞으로 수동으로 매개변수를 바꾸는 대신에, 그리드 서치나 랜덤 서치를 사용해야겠다!\n'